# Generated by Django 5.2.1 on 2025-05-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakesTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='cake',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cakestypes'),
        ),
    ]
