# Generated by Django 5.2.1 on 2025-05-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0003_rename_nombre_categoria_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakestypes',
            old_name='category_id',
            new_name='category',
        ),
    ]
