# Generated by Django 5.2.1 on 2025-05-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0006_cake_precio_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='articulo_nuevo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='oferta',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
