# Generated by Django 5.2.1 on 2025-05-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0007_cake_articulo_nuevo_cake_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='articulo_nuevo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='oferta',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
