# Generated by Django 5.2.1 on 2025-05-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0008_alter_cake_articulo_nuevo_alter_cake_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='agotado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='articulo_nuevo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
