# Generated by Django 5.2.1 on 2025-06-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0009_cake_agotado_alter_cake_articulo_nuevo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='precio_anterior',
            new_name='after_prince',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='disponible',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='creado_en',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='ocultar',
            new_name='hidden',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='articulo_nuevo',
            new_name='new_article',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='oferta',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='precio',
            new_name='prince',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='agotado',
            new_name='sold',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='precio_unitario',
            new_name='prince_unitario',
        ),
    ]
